'use client';

import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Product, Manufacturer } from '@/lib/types';

interface ManufacturerAnalyticsProps {
  manufacturer: Manufacturer;
  products: Product[];
}

const COLORS = ['#3b82f6', '#10b981', '#8b5cf6', '#f59e0b', '#ef4444', '#06b6d4', '#8b5cf6'];

const ManufacturerAnalytics: React.FC<ManufacturerAnalyticsProps> = ({ manufacturer, products }) => {
  // Calculate analytics data
 const totalProducts = products.length;
  const totalRevenue = products.reduce((sum, product) => {
    const productRevenue = (product.price || 0) * (product.totalSold || 0);
    return sum + productRevenue;
  }, 0);
  const totalStock = products.reduce((sum, product) => sum + (product.stock || 0), 0);
  const avgPrice = totalProducts > 0 ? totalRevenue / totalProducts : 0;

  // Prepare data for top-selling products chart
 const topSellingProducts = [...products]
    .sort((a, b) => (b.totalSold || 0) - (a.totalSold || 0))
    .slice(0, 5)
    .map(product => ({
      name: product.name,
      sold: product.totalSold || 0,
      revenue: (product.price || 0) * (product.totalSold || 0),
    }));

  // Prepare data for stock level chart
  const stockLevelData = products.map(product => ({
    name: product.name,
    stock: product.stock || 0,
    price: product.price || 0,
  }));

  // Prepare data for category distribution pie chart
  const categoryDistribution = products.reduce((acc: Record<string, number>, product) => {
    const category = product.category || 'Uncategorized';
    acc[category] = (acc[category] || 0) + 1;
    return acc;
  }, {});
  
  const categoryData = Object.entries(categoryDistribution).map(([name, value]) => ({
    name,
    value,
  }));

  return (
    <div className="space-y-6">
      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total Products</CardDescription>
            <CardTitle className="text-2xl">{totalProducts}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-xs text-muted-foreground">
              Products under this manufacturer
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total Revenue</CardDescription>
            <CardTitle className="text-2xl">${totalRevenue.toFixed(2)}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-xs text-muted-foreground">
              Generated by this manufacturer
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total Stock</CardDescription>
            <CardTitle className="text-2xl">{totalStock}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-xs text-muted-foreground">
              Units currently in stock
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Average Price</CardDescription>
            <CardTitle className="text-2xl">${avgPrice.toFixed(2)}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-xs text-muted-foreground">
              Average price per product
            </div>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Top Selling Products */}
      <div className="space-y-2">
        <h3 className="text-lg font-semibold">Top Selling Products</h3>
        <Card>
          <CardContent className="p-4">
            <ResponsiveContainer width="100%" height={300}>
              <BarChart
                data={topSellingProducts}
                margin={{ top: 20, right: 30, left: 20, bottom: 50 }}
              >
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" angle={-45} textAnchor="end" height={60} />
                <YAxis />
                <Tooltip 
                  formatter={(value, name) => 
                    name === 'sold' ? [value, 'Units Sold'] : [`$${value}`, 'Revenue']
                  }
                />
                <Legend />
                <Bar dataKey="sold" name="Units Sold" fill="#3b82f6" />
                <Bar dataKey="revenue" name="Revenue ($)" fill="#10b981" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Stock Levels */}
      <div className="space-y-2">
        <h3 className="text-lg font-semibold">Product Stock Levels</h3>
        <Card>
          <CardContent className="p-4">
            <ResponsiveContainer width="100%" height={300}>
              <BarChart
                data={stockLevelData}
                margin={{ top: 20, right: 30, left: 20, bottom: 50 }}
              >
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" angle={-45} textAnchor="end" height={60} />
                <YAxis />
                <Tooltip />
                <Legend />
                <Bar dataKey="stock" name="Stock Level" fill="#8b5cf6" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Category Distribution */}
      <div className="space-y-2">
        <h3 className="text-lg font-semibold">Category Distribution</h3>
        <Card>
          <CardContent className="p-4">
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie
                  data={categoryData}
                  cx="50%"
                  cy="50%"
                  labelLine={true}
                  label={({ name, percent }) => `${name} ${(percent * 10).toFixed(0)}%`}
                  outerRadius={80}
                  fill="#884d8"
                  dataKey="value"
                >
                  {categoryData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Manufacturer Details */}
      <div className="space-y-2">
        <h3 className="text-lg font-semibold">Manufacturer Details</h3>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-4">
              {manufacturer.icon && (
                <div 
                  className="w-16 h-16 rounded-lg flex items-center justify-center text-2xl"
                  style={{ backgroundColor: manufacturer.color }}
                >
                  {manufacturer.icon}
                </div>
              )}
              <div>
                <h4 className="text-xl font-bold">{manufacturer.name}</h4>
                <p className="text-muted-foreground">{manufacturer.description}</p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {manufacturer.tags?.map((tag, index) => (
                    <Badge key={index} variant="secondary">{tag}</Badge>
                  ))}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default ManufacturerAnalytics;