import { z } from "zod";

export const drillSchemas = {
  revenue: z.object({
    value: z.string().optional(),
    granularity: z.enum(["day", "week", "month", "year"]).optional(),
    amount: z.number().optional(),
  }),
  product: z.object({
    id: z.string(),
    name: z.string().optional(),
    stock: z.number().optional(),
    price: z.number().optional(),
  }),
  company: z.object({
    id: z.string(),
    name: z.string().optional(),
    status: z.string().optional(),
    phoneNumber: z.string().optional(),
  }),
  order: z.object({
    id: z.string(),
    total: z.number().optional(),
  }),
  maintenance: z.object({
    id: z.string(),
    branchId: z.string().optional(),
    branchName: z.string().optional(),
    companyId: z.string().optional(),
    companyName: z.string().optional(),
    date: z.string().optional(),
    technicianName: z.string().optional(),
    status: z.string().optional(),
    totalCost: z.number().optional(),
    notes: z.string().optional(),
    rating: z.number().optional(),
  }),
  inventory: z.object({
    id: z.string().optional(),
  }),
  customer: z.object({
    id: z.string().optional(),
  }),
  barista: z.object({
    id: z.string(),
    name: z.string().optional(),
    branchId: z.string().optional(),
    branchName: z.string().optional(),
    rating: z.number().optional(),
    phoneNumber: z.string().optional(),
  }),
  branch: z.object({
    id: z.string(),
    name: z.string().optional(),
    companyId: z.string().optional(),
    companyName: z.string().optional(),
    location: z.string().optional(),
    performanceScore: z.number().optional(),
    machineOwned: z.boolean().optional(),
    phoneNumber: z.string().optional(),
  }),
  manufacturer: z.object({
    id: z.string(),
    name: z.string().optional(),
    icon: z.string().optional(),
    productCount: z.number().optional(),
    phoneNumber: z.string().optional(),
  }),
  category: z.object({
    id: z.string(),
    name: z.string().optional(),
    productCount: z.number().optional(),
    revenue: z.number().optional(),
  }),
  feedback: z.object({
    id: z.string(),
    clientId: z.string().optional(),
    clientName: z.string().optional(),
    rating: z.number().optional(),
    sentiment: z.enum(["positive", "negative", "neutral"]).optional(),
    message: z.string().optional(),
    feedbackDate: z.string().optional(),
  }),
  notification: z.object({
    id: z.string(),
    title: z.string().optional(),
    message: z.string().optional(),
    priority: z.enum(["critical", "warning", "info"]).optional(),
    icon: z.string().optional(),
    source: z.string().optional(),
    createdAt: z.string().optional(),
    read: z.boolean().optional(),
    snoozedUntil: z.string().optional(),
    actionType: z.any().optional(),
    entityId: z.string().optional(),
    link: z.string().optional(),
    metadata: z.object({
      entityType: z.string().optional(),
      entityId: z.string().optional(),
      amount: z.number().optional(),
      daysUntil: z.number().optional(),
      clientName: z.string().optional(),
      orderCount: z.number().optional(),
    }).optional(),
  }),
  payment: z.object({
    id: z.string(),
    orderId: z.string(),
    companyId: z.string().optional(),
    companyName: z.string().optional(),
    amount: z.number().optional(),
    paidDate: z.string().optional(),
    paymentMethod: z.enum(["transfer", "check"]).optional(),
    paymentReference: z.string().optional(),
    paymentNotes: z.string().optional(),
  }),
};
